#!/usr/bin/env python3
"""bump_version.py — release helper for PokeClaude's VERSION + CHANGELOG.md.

    python3 scripts/bump_version.py major|minor|patch|X.Y.Z [--dry-run]
    python3 scripts/bump_version.py --release-current [--dry-run]
    python3 scripts/bump_version.py --extract-notes X.Y.Z

Owns exactly three things:

1. Bumping VERSION and moving CHANGELOG.md's "## [Unreleased]" content into
   a new dated "## [X.Y.Z] - YYYY-MM-DD" section (leaving [Unreleased]
   empty), then rewriting the compare/tag links at the bottom of the file.
2. `--release-current`, a one-time helper for the very first release: it
   just dates the existing "## [0.1.0] - TBD" section instead of moving
   anything out of [Unreleased] (there's nothing to move on a first
   release — 0.1.0's notes were written directly).
3. `--extract-notes X.Y.Z`, which prints one version's changelog section to
   stdout so the release workflow can hand it to `gh release create
   --notes-file`.

This script never touches git. It prints the commands to run next and lets
the person (or the CI workflow) run them.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path
from typing import Optional

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_VERSION_PATH = PROJECT_ROOT / "VERSION"
DEFAULT_CHANGELOG_PATH = PROJECT_ROOT / "CHANGELOG.md"
REPO_URL = "https://github.com/ChrisPatten/pokeclaude"

SEMVER_RE = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")
_HEADER_RE = re.compile(r"^## \[([^\]]+)\](?: - (.*?))?\s*$")
_LINK_RE = re.compile(r"^\[([^\]]+)\]:\s*(\S+)\s*$")


class BumpError(Exception):
    """Raised for any user-fixable problem; main() prints it and exits 1."""


# ---------------------------------------------------------------------------
# SemVer math
# ---------------------------------------------------------------------------


def parse_semver(version: str) -> tuple[int, int, int]:
    match = SEMVER_RE.match(version.strip())
    if not match:
        raise BumpError(
            f"Invalid semantic version: {version!r} (expected MAJOR.MINOR.PATCH, e.g. 1.2.3)"
        )
    major, minor, patch = (int(part) for part in match.groups())
    return major, minor, patch


def compute_new_version(current_version: str, bump: str) -> str:
    """``bump`` is 'major', 'minor', 'patch', or an explicit X.Y.Z string."""
    if bump in ("major", "minor", "patch"):
        major, minor, patch = parse_semver(current_version)
        if bump == "major":
            return f"{major + 1}.0.0"
        if bump == "minor":
            return f"{major}.{minor + 1}.0"
        return f"{major}.{minor}.{patch + 1}"
    parse_semver(bump)  # validates format; raises BumpError if malformed
    return bump


# ---------------------------------------------------------------------------
# CHANGELOG.md parsing
# ---------------------------------------------------------------------------


class Section:
    __slots__ = ("version", "date", "body")

    def __init__(self, version: str, date_str: str, body: str):
        self.version = version
        self.date = date_str  # "" for a bare "## [Unreleased]" header, else "YYYY-MM-DD" or "TBD"
        self.body = body


def parse_changelog(text: str) -> tuple[str, list[Section], list[str]]:
    """Returns (preamble, sections, link_ref_keys_in_order).

    ``sections`` covers every "## [...]" heading in document order (so
    "Unreleased" first, most recent release next, etc). The trailing
    reference-style link block ("[X.Y.Z]: https://...") is parsed separately
    and always regenerated by ``rewrite_links`` rather than preserved
    verbatim, since it's derived data.
    """
    lines = text.splitlines(keepends=True)

    header_positions: list[tuple[int, str, str]] = []
    for i, line in enumerate(lines):
        match = _HEADER_RE.match(line)
        if match:
            header_positions.append((i, match.group(1), (match.group(2) or "").strip()))

    if not header_positions:
        raise BumpError("No '## [...]' sections found in changelog")

    preamble = "".join(lines[: header_positions[0][0]])

    # The link-reference block is the trailing run of "[Key]: url" lines
    # (and blank lines among them) that starts after the last heading.
    link_start = len(lines)
    for i in range(header_positions[-1][0], len(lines)):
        if _LINK_RE.match(lines[i]):
            link_start = i
            break

    sections: list[Section] = []
    for idx, (line_i, version, date_str) in enumerate(header_positions):
        body_start = line_i + 1
        body_end = header_positions[idx + 1][0] if idx + 1 < len(header_positions) else link_start
        sections.append(Section(version, date_str, "".join(lines[body_start:body_end])))

    order: list[str] = []
    for line in lines[link_start:]:
        match = _LINK_RE.match(line)
        if match:
            order.append(match.group(1))

    return preamble, sections, order


def render_changelog(preamble: str, sections: list[Section], links: dict[str, str], order: list[str]) -> str:
    parts = [preamble]
    for section in sections:
        header = f"## [{section.version}]" + (f" - {section.date}" if section.date else "")
        parts.append(header + "\n")
        parts.append(section.body)
    for key in order:
        parts.append(f"[{key}]: {links[key]}\n")
    return "".join(parts)


def unreleased_is_empty(body: str) -> bool:
    return not any(line.strip() for line in body.splitlines())


def rewrite_links(sections: list[Section], repo_url: str = REPO_URL) -> tuple[dict[str, str], list[str]]:
    """Rebuild compare/tag links to match Keep a Changelog convention:

        [Unreleased]: {repo}/compare/vLATEST...HEAD
        [X.Y.Z]: {repo}/compare/vPREV...vX.Y.Z
        [OLDEST]: {repo}/releases/tag/vOLDEST
    """
    links: dict[str, str] = {}
    order: list[str] = []
    for i, section in enumerate(sections):
        version = section.version
        order.append(version)
        if version == "Unreleased":
            if len(sections) > 1:
                latest = sections[1].version
                links[version] = f"{repo_url}/compare/v{latest}...HEAD"
            else:
                links[version] = f"{repo_url}/commits/HEAD"
        elif i + 1 < len(sections):
            prev = sections[i + 1].version
            links[version] = f"{repo_url}/compare/v{prev}...v{version}"
        else:
            links[version] = f"{repo_url}/releases/tag/v{version}"
    return links, order


# ---------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------


def bump_changelog(text: str, new_version: str, date_str: str, allow_empty: bool = False) -> str:
    preamble, sections, _ = parse_changelog(text)
    if sections[0].version != "Unreleased":
        raise BumpError("Expected the changelog's first section to be '## [Unreleased]'")

    if any(s.version == new_version for s in sections):
        raise BumpError(f"CHANGELOG.md already has a section for {new_version}")

    unreleased_body = sections[0].body
    if not allow_empty and unreleased_is_empty(unreleased_body):
        raise BumpError(
            "'[Unreleased]' section is empty; add changelog entries first, "
            "or pass --allow-empty to bump anyway."
        )

    new_section = Section(new_version, date_str, unreleased_body if unreleased_body.strip() else "\n")
    sections[0].body = "\n"
    sections.insert(1, new_section)

    links, order = rewrite_links(sections)
    return render_changelog(preamble, sections, links, order)


def release_current_changelog(text: str, current_version: str, date_str: str) -> str:
    preamble, sections, _ = parse_changelog(text)
    target = next((s for s in sections if s.version == current_version), None)
    if target is None:
        raise BumpError(f"No '## [{current_version}]' section found in CHANGELOG.md")
    if target.date.strip().upper() != "TBD":
        raise BumpError(
            f"'## [{current_version}]' is dated {target.date!r}, not 'TBD' — "
            "--release-current is only for dating the first release."
        )
    target.date = date_str

    links, order = rewrite_links(sections)
    return render_changelog(preamble, sections, links, order)


def extract_notes(text: str, version: str) -> str:
    _, sections, _ = parse_changelog(text)
    for section in sections:
        if section.version == version:
            body = section.body.strip("\n")
            return f"{body}\n" if body else ""
    raise BumpError(f"No changelog section found for version {version!r}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "bump", nargs="?", help="'major', 'minor', 'patch', or an explicit X.Y.Z"
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="print what would change without writing files"
    )
    parser.add_argument(
        "--allow-empty",
        action="store_true",
        help="bump even if the '[Unreleased]' section has no entries",
    )
    parser.add_argument(
        "--release-current",
        action="store_true",
        help="date the existing '[<VERSION>] - TBD' section instead of bumping (first release only)",
    )
    parser.add_argument(
        "--extract-notes",
        metavar="X.Y.Z",
        help="print that version's changelog section to stdout and exit (no files touched)",
    )
    parser.add_argument(
        "--version-file", default=str(DEFAULT_VERSION_PATH), help=argparse.SUPPRESS
    )
    parser.add_argument(
        "--changelog-file", default=str(DEFAULT_CHANGELOG_PATH), help=argparse.SUPPRESS
    )
    return parser


def main(argv: Optional[list[str]] = None) -> int:
    args = _build_parser().parse_args(argv)
    version_path = Path(args.version_file)
    changelog_path = Path(args.changelog_file)

    try:
        if args.extract_notes:
            changelog_text = changelog_path.read_text(encoding="utf-8")
            sys.stdout.write(extract_notes(changelog_text, args.extract_notes))
            return 0

        current_version = version_path.read_text(encoding="utf-8").strip()
        changelog_text = changelog_path.read_text(encoding="utf-8")
        today = date.today().isoformat()

        if args.release_current:
            new_changelog = release_current_changelog(changelog_text, current_version, today)
            new_version = current_version
        else:
            if not args.bump:
                raise BumpError("Missing argument: major|minor|patch|X.Y.Z (or use --release-current)")
            new_version = compute_new_version(current_version, args.bump)
            new_changelog = bump_changelog(
                changelog_text, new_version, today, allow_empty=args.allow_empty
            )
    except BumpError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.dry_run:
        print(f"Would set VERSION to {new_version}")
        print("Would rewrite CHANGELOG.md:")
        print(new_changelog)
        return 0

    version_path.write_text(new_version + "\n", encoding="utf-8")
    changelog_path.write_text(new_changelog, encoding="utf-8")

    print(f"VERSION -> {new_version}")
    print(f"CHANGELOG.md updated ({changelog_path}).")
    print()
    print("Next steps:")
    print(f"  git add {version_path.name} {changelog_path.name}")
    print(f'  git commit -m "Release v{new_version}"')
    print(f'  git tag -a v{new_version} -m "v{new_version}"')
    print("  git push origin main --tags")
    return 0


if __name__ == "__main__":
    sys.exit(main())
